openapi: 3.0.0
info:
    description: 'A Sample application using Typescipt-rest library'
    license:
        name: MIT
    title: Typescript-rest
    version: 0.0.1
paths:
    '/account/{accountID}':
        get:
            operationId: AccountFindById
            responses:
                '200':
                    description: 'Retrieve an account information'
                    content:
                        'application/json; charset=utf-8':
                            schema:
                                $ref: '#/components/schemas/Account'
                '404':
                    description: 'Account not found'
            description: ""
            parameters:
                -
                    description: ""
                    in: path
                    name: accountID
                    required: true
                    schema:
                        type: string
    /account:
        get:
            operationId: AccountGetAll
            responses:
                '200':
                    description: Ok
                    content:
                        'application/json; charset=utf-8':
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Account'
            description: ""
components:
    securitySchemes:
        default:
            type: apiKey
            in: header
            name: Authorization
        secondAuthenticator:
            type: apiKey
            in: header
            name: Authorization
    schemas:
        Account:
            description: ""
            properties:
                id:
                    type: integer
                    format: int32
                    description: 'The accounts''s id'
                balance:
                    type: number
                    format: float
                    description: 'Account''s total amount'
                accountType:
                    type: string
                    description: 'Account Type'
            type: object
            required:
                - id
                - balance
                - accountType
