image: gradle:6.7.0-jdk11

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  API_TOKEN: $GLOBAL_ACCESS_TOKEN
  PROVIDER_PROJECT_ID: 3
  PROVIDER_PIPELINE_TOKEN: $PROVIDER_ORANGE_STACK_CI_TOKEN
  TARGET_BRANCH: master
  MAVEN_REPO: /cache/.m2
  GRADLE_USER_HOME: /cache/.gradle


stages:
  - test-and-publish-contract
  - check-provider

cache:
  paths:
    - .gradle

test-and-publish-contract:
  stage: test-and-publish-contract
  script:
    - gradle clean wrapper test --tests br.com.zup.pact.consumer.pact.ShoppingCartContractTest
    - gradle pactPublish

check-provider:
  stage: check-provider
  image: registry.gitlab.com/finestructure/pipeline-trigger
  before_script:
    - echo "Triggering Pipeline from Provider to check contract"
  script: 
    - trigger -h "http://172.20.1.2" -a "$API_TOKEN" -p "$PROVIDER_PIPELINE_TOKEN" -t $TARGET_BRANCH $PROVIDER_PROJECT_ID

