#micronaut:
#  application:
#    name: provider
#  server:
#    port: 8081
#grpc:
#  server:
#    port: 6565

##pactbroker:
##  host: localhost
##  port: 9292
##  protocol: http
##
#micronaut:
#  application:
#    name: provider
#  server:
#    port: 8081
#
##grpc:
##  server:
##    port: 6565