image: gradle:6.7.0-jdk11
stages:
  - check-consumer

variables:
  MAVEN_REPO: /cache/.m2
  GRADLE_USER_HOME: /cache/.gradle

cache:
  paths:
    - .gradle

check-consumer:
  stage: check-consumer
  script:
    - gradle clean wrapper test --tests br.com.zup.pact.provider.pact.ShoppingCartProviderPactTest
